POST http://localhost:3001/api/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "user 1",
    "email": "user@gmail.com",
    "password": "user123"
}


###
POST http://localhost:3001/api/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "user 1",
    "password": "user123"
}


###
PUT http://localhost:3001/api/user/pmp6jWuGYfPGS4FdlgQtWzKHHug1/update-email-and-username HTTP/1.1
content-type: application/json

{
    "newUsername": "user 1",
    "newEmail": "user@gmail.com"
}

 

###
PUT http://localhost:3001/api/user/pmp6jWuGYfPGS4FdlgQtWzKHHug1/update-password HTTP/1.1
content-type: application/json

{
    "newPassword": "user123"
}



###
GET http://localhost:3001/api/category/id1 HTTP/1.1

###
POST http://localhost:3001/api/category/create HTTP/1.1
content-type: application/json

{
    "userid": "1",
    "name": "cat 2",
    "color": "color 1",
    "icon": "icon 1",
    "TransactionType": "Income"
}

###
PUT http://localhost:3001/api/category/cnLZ7Gbuyy1RRI8Wx30E HTTP/1.1
content-type: application/json

{
    
    "icon": "icon 2",
    "TransactionType": "Expense"
}

###
DELETE  http://localhost:3001/api/category/nwz5ukswrZteheSd2Wos HTTP/1.1


###
GET http://localhost:3001/api/transaction/id1 HTTP/1.1

###
POST http://localhost:3001/api/transaction/create HTTP/1.1
content-type: application/json

{
    "userid": "id1",
    "name": "name 4",
    "amount": 6000.00,
    "type": "Income",
    "categoryId": "cnLZ7Gbuyy1RRI8Wx30E",
    "isRecurring": true
}

###
PUT http://localhost:3001/api/transaction/OFqTpwdGEycllBVabgIV HTTP/1.1
content-type: application/json

{    
    "isRecurring": false
}

###
GET http://localhost:3001/api/goal/id1 HTTP/1.1

###
POST http://localhost:3001/api/goal/create HTTP/1.1
content-type: application/json

{
    "userid": "id1",
    "name": "name 1",
    "target_amount": 2100.00,
    "current_amount": 0.00,
    "Deadline": "12/12/2024",
    "contribution_type": "monthly",
    "contribution_amount": 21.57
}



###
GET http://localhost:3001/api/analytics/id1/transactions/monthly HTTP/1.1

###
GET http://localhost:3001/api/analytics/id1/categories HTTP/1.1

###
GET http://localhost:3001/api/investment HTTP/1.1

###
GET http://localhost:3001/api/investment/update/logo HTTP/1.1

###
GET http://localhost:3001/api/investment/AAPL HTTP/1.1

###
GET http://localhost:3001/api/investment/top/stocks HTTP/1.1

###
GET http://localhost:3001/api/investment/top/batch-stocks HTTP/1.1

###
GET http://localhost:3001/api/investment/top/40 HTTP/1.1

###
POST http://localhost:3001/api/translation/en/af/translate HTTP/1.1
content-type: application/json

{
    "text": "hello, my name is nathi"
}


###
GET http://localhost:3001/api/notification/pmp6jWuGYfPGS4FdlgQtWzKHHug1 HTTP/1.1


###
PUT http://localhost:3001/api/notification/pmp6jWuGYfPGS4FdlgQtWzKHHug1/register-token HTTP/1.1
content-type: application/json

{
    "fcmToken": "mockToken123"
}


###
POST http://localhost:3001/api/notification/create HTTP/1.1
content-type: application/json

{
    "userid": "pmp6jWuGYfPGS4FdlgQtWzKHHug1",
    "title": "new goal",
    "message": "goal 'new car' created successfully"
}

###
PUT http://localhost:3001/api/notification/4U7RDCEwizoCGEgPyNn2 HTTP/1.1
