GET http://localhost:3001/api/category/id1 HTTP/1.1

###
POST http://localhost:3001/api/category/create HTTP/1.1
content-type: application/json

{
    "userid": "1",
    "name": "cat 2",
    "color": "color 1",
    "icon": "icon 1",
    "TransactionType": "Income"
}

###
PUT http://localhost:3001/api/category/cnLZ7Gbuyy1RRI8Wx30E HTTP/1.1
content-type: application/json

{
    
    "icon": "icon 2",
    "TransactionType": "Expense"
}

###
DELETE  http://localhost:3001/api/category/nwz5ukswrZteheSd2Wos HTTP/1.1


###
GET http://localhost:3001/api/transaction/id1 HTTP/1.1

###
POST http://localhost:3001/api/transaction/create HTTP/1.1
content-type: application/json

{
    "userid": "id1",
    "name": "name 4",
    "amount": 6000.00,
    "type": "Income",
    "categoryId": "cnLZ7Gbuyy1RRI8Wx30E",
    "isRecurring": true
}

###
PUT http://localhost:3001/api/transaction/OFqTpwdGEycllBVabgIV HTTP/1.1
content-type: application/json

{    
    "isRecurring": false
}

###
GET http://localhost:3001/api/goal/id1 HTTP/1.1

###
POST http://localhost:3001/api/goal/create HTTP/1.1
content-type: application/json

{
    "userid": "id1",
    "name": "name 1",
    "target_amount": 2100.00,
    "current_amount": 0.00,
    "Deadline": "12/12/2024",
    "contribution_type": "monthly",
    "contribution_amount": 21.57
}



###
GET http://localhost:3001/api/analytics/id1/transactions/monthly HTTP/1.1

###
GET http://localhost:3001/api/analytics/id1/categories HTTP/1.1



###
POST http://localhost:3001/api/translation/en/af/translate HTTP/1.1
content-type: application/json

{
    "text": "hello, my name is nathi"
}